# Generated by Django 3.2.5 on 2021-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_responselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
    ]
